### PR TITLE
fix: show assets with maxed out debt cieling in borrow list

### LINKED ISSUE #1347: fix: display and warnings for isolated assets
**Describe the bug**

If an asset has a maxed-out debt ceiling, it currently blocks the asset from displaying in the supply and borrow sections. The asset should always be available to supply or borrow with one exception: if a user is supplying the asset *in* isolation mode, they cannot supply additional collateral with a different asset.

Also remove debt ceiling warning from borrow modal. Not relevant since debt ceiling only affects usage of asset as collateral.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by grothem**
## General Changes

- Fixes #1347 

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [x]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [x]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by grothem** [comment]
Link T-3457

File: src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx [hunk 1]
```diff
@@ -32,10 +31,6 @@ export const BorrowAssetsListItem = ({
   const { currentMarket } = useProtocolDataContext();
   const borrowButtonDisable = isFreezed || Number(availableBorrows) <= 0;
 
-  // Hide the asset to prevent it from being borrowed if borrow cap has been reached
-  const { borrowCap: borrowCapUsage, debtCeiling } = useAssetCaps();
```
Comment (defispartan) [inline src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx:36]: What will happen if an asset has reached the max borrow cap, will it still show up in the borrow positions and asset lists with a warning?

Comment (grothem) [reply src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx:36]: Looks like it'll show up in the list with a warning/tooltip
image

**Review by defispartan — DISMISSED** [review]

**Review by defispartan — APPROVED** [review]

**Review by MareskoY — APPROVED** [review]
