### PR TITLE
fix: error message for assets with flashloan disabled [skip cypress]

### LINKED ISSUE #1880: Switch features do not factor flashloanable flag in V3
**Describe the bug**

Reserves in Aave V3 have a parameter isFlashloanable which is separate from borrowing enabled. 

Collateral switch (and potentially other featuresl) do not have a warning if a flashloan is attempted and the reserve does not support. The max amount should account for whether flashloan can be used.

**To Reproduce**

Supply reserve with flashloanEnabled = false ($AAVE on V3 Ethereum market) -> Open borrow position with low health factor -> attempt to collateral switch full balance

A flashloan will be attempted and txn will fail gas estimation

### PR DESCRIPTION
**Pull request by grothem**
## General Changes

- Adds in an message on why an asset cannot be used for a switch if flash loan is disabled
- Fixes #1880 

## Developer Notes

Add any notes here that may be helpful for reviewers.

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [ ]  The base branch is set to `main`
- [ ]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [ ]  The General Changes section has been filled out
- [ ]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [ ]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Review by foodaka — DISMISSED** [review]

File: src/components/transactions/Repay/CollateralRepayModalContent.tsx [hunk 1]
```diff
@@ -202,6 +204,13 @@ export function CollateralRepayModalContent({
             collateral to perform this action
           </Trans>
         );
+      case ErrorType.FLASH_LOAN_NOT_AVAILABLE:
+        return (
+          <Trans>
+            A flash loan is required to perform the repay, but this asset is not availalbe to use
```
Comment (defispartan) [inline src/components/transactions/Repay/CollateralRepayModalContent.tsx:210]: Due to health factor impact, a flashloan is required to perform this transaction, but Aave Governance has disabled flashloan availability for this asset. Try lowering the amount or supplying additional collateral.

File: src/components/transactions/Swap/SwapModalContent.tsx [hunk 2]
```diff
@@ -152,6 +152,13 @@ export const SwapModalContent = ({
             collateral to perform this action
           </Trans>
         );
+      case ErrorType.FLASH_LOAN_NOT_AVAILABLE:
```
Comment (defispartan) [inline src/components/transactions/Swap/SwapModalContent.tsx:155]: I think the error condition needs to be added in this file as well
```
else if (shouldUseFlashloan && !collateralReserveData.flashLoanEnabled) {
    blockingError = ErrorType.FLASH_LOAN_NOT_AVAILABLE;
  }
 ```

Comment (grothem) [reply src/components/transactions/Swap/SwapModalContent.tsx:157]: good catch, added

**Review by defispartan — DISMISSED** [review]

**Review by foodaka — APPROVED** [review]

**Review by defispartan — APPROVED** [review]

**Review by foodaka — APPROVED** [review]
